import './globals.css';

export const metadata = {
  title: 'Apple iPhone',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/images/apple.svg', // Path to your SVG file
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
